### PR TITLE
test(QUnit 2.0.0)

### PR DESCRIPTION
**Pull request by arjunkathuria**
upgrades the test harness and cases from QUnit 1.14.0 to QUnit 2.0.0, also upgrades asset jQuery to 3.0.0 .

### CODE REVIEW

**Comment by arjunkathuria** [comment]
@arschmitz @runspired

**Comment by arschmitz** [comment]
There are lots of style issues with this PR all the quotes were converted to double quotes spacing issues etc. If you address my comments about the gruntfile in #1000 you will find all the style issues so i wont bother going into all the style issues.

**Comment by arschmitz** [comment]
Seems to me like we should also move jQuery, QUnit, lodash, and blanket to be managed through npm instead of manual copying. If we want to keep the location we can use something like https://www.npmjs.com/package/grunt-npmcopy to update them with a grunt task. 

We also need to make sure we include the license files along with these.

**Comment by arschmitz** [comment]
Iv gone through quickly and don't see anything else so far but many of these changes will go away once style issues are fixed and or look completely different.

**Comment by arjunkathuria** [comment]
@arschmitz updated.

what's included:-
- Fix styling issues eg:- correct quotes, spacing etc.
- Updates Gruntfile.
- jshint source, test files & Gruntfile.
- jscs test files & Gruntfile.
- updated node to latest.
- updated editorconf.

**Comment by arschmitz** [comment]
> jscs test files & Gruntfile.

These are only passing because you added a pile of ignore's please remove these and update the code properly

I would also still like to see the test assets managed through npm

**Comment by arschmitz** [comment]
> updated node to latest.
> updated editorconf.

these should really be a separate commit

**Comment by arjunkathuria** [comment]
@arschmitz slack please?

**Comment by runspired** [comment]
@arschmitz looks like we've iterated to success, yes?

**Comment by arschmitz** [comment]
Yes im happy with this now 👍

**Pull request merged**
