### PR TITLE
[WIP] npm-scripts

### PR DESCRIPTION
**Pull request by arjunkathuria**
PR for npm-scripts written to replace grunt and grunt tasks in the project and thus removing the dependency on grunt as a build tool.

Done:-

- npm scripts to perform tasks currently done via grunt.
  * bannerize (adds the banner ).
  * connect (serves the project on port 8000).
  * rollup (executes rollup.js).
  * uglify (uglifies and produces the min and map files).
  * string-replace (replaces {{PKG_VERSION}} with version in dist).
  * jshint (runs jshint).
  * jscs (runs jscs).
  * qunit (runs qunit).
  * watch (watch for changes in files and execute watch-tasks when changed).
  * watch-tasks (collective of tasks to be performed when a watched file changes).
  * test (collective task for jshint, jscs & qunit).
  * build (collective task for rollup, string-replace, uglify, bannerize and test).
  * test-travis (task for travis CI).

Todo:-

-  ~~Remove grunt and related stuff from package.json after review.~~
-  add \ remove, tasks \ config files as per review.
- ??? : )

cc:- @arschmitz @runspired

### CODE REVIEW

**Comment by runspired** [comment]
@arschmitz I think we are 👍

**Comment by arschmitz** [comment]
👍

**Comment by arjunkathuria** [comment]
@arschmitz @runspired Gentlemen, shall we

**Comment by runspired** [comment]
We shall.

**Pull request merged**
