### PR TITLE
Add a window option

### PR DESCRIPTION
**Pull request by denis-sokolov**
An idea for window option, previously discussed in #597.

### CODE REVIEW

**Comment by arschmitz** [comment]
@denis-sokolov just reading up on this going through old pr's i would be more inclined to do something like this 
```js
this.window = this.document[ 0 ].defaultView || this.document[ 0 ].parentWindow;
```
within the manager this would ensure the manager always gets the correct window for the context in which it is executed. Then you can just make sure you call each hammer instance in the proper context and it will also get the proper window. Would this address your issue?

**Comment by denis-sokolov** [comment]
Although I think that semantically it makes sense to pass `window` separately (element can be detached, it can move between windows), in practice this would work.

**Comment by arschmitz** [comment]
@denis-sokolov so the method i posted works on detached elements just fine i'm a little un sure on if it makes sense to allow passing of things between windows though why would you instantiate it in one window and pass it to another what is your use case for this?

**Comment by runspired** [comment]
@arschmitz one potential use case is for an ability I'll be bringing to ember apps mid to late fall: threaded rendering and iframe storage.  Essentially you get a route stack so you can pull screens onto or off of the stack at any time to make transitions seamless.  The html is pre-generated in web-workers or server side and stored as documentFragments in an iframe.  It makes sense to do a lot of the setup for the screen in the iframe.

**Comment by arschmitz** [comment]
@runspired Ok i can buy that

**Comment by runspired** [comment]
@denis-sokolov We'd be willing to take this for a minor release to follow the patch release we're about to send out, but it would need to be completed.

The blocker is the patch release and that's going out TODAY, so the sooner you can clean this up the better :)

**Comment by arschmitz** [comment]
@denis-sokolov any chance you could update this to remove the conflicts we released the patch version blocking this and i would like to get it merged

**Comment by denis-sokolov** [comment]
I'm sorry, I don't think I'm interested anymore. :(

**Comment by darrennolan** [comment]
@arschmitz - Can I be of assistance?  

Because of the reliance of the global window object, it makes hammerJS impossible to use under nodeJS.  Just reading the thread here, if we can hand in a stub for window (when code is running on nodejs vs the browser) - that would solve our current issues for our universal/isomorphic code.

Let me know.  

Cheers,

**Comment by arschmitz** [comment]
@darrennolan can you explain what your looking for?

**Comment by darrennolan** [comment]
Sorry @arschmitz - was in a mad rush this morning to fix this.

https://github.com/FoxSportsAustralia/hammer.js/commit/a3a3935494d86f0e7d419f4a815062f1ef3069a0 is what i've done very short term until I can set some time aside and work out how best to implement this properly for nodeJS.

Basically our code is universal/isomorphic - that is code that runs both on the client browser, and code that runs under nodejs (we render on the server side as well as the client browser).  

With hammer.js - we don't actually use it while under node, but it'll still cause the main process to crash with window/document being undefined as it's included in our bundles.

Hope that clears up what I mean :)

**Comment by arschmitz** [comment]
If im following correctly what your actually doing there with the change to prefix is just making hammer entirely a noop if document or window are undefined? this does not seem like something that would make sense to add and is more something to answer through your own build system / wrapper.

Also on a side note that commit removes the copyright and license header from hammer which is a violation of the license and copyright laws. So if you could please add that back in to the copy your using that would be great :-)

**Comment by darrennolan** [comment]
:O I removed something?!  Oh, that may have been a compile issue.  See https://github.com/hammerjs/hammer.js/issues/787 - I just fixed that up by hand. Sorry sorry! ^_^

**Comment by arschmitz** [comment]
Thank you for fixing that quickly and no problem i didn't think it was malicious just wanted to point it out.

**Comment by darrennolan** [comment]
RE: Giant noop when no window/document discovered.  Well, yes. hammer.js can't work without these two things - but that shouldn't stop or throw exceptions when an application is using it.  

What that fork/branch is provides only a short-term fix to get us moving along today.  Certainly not the ideal solution.

>  this does not seem like something that would make sense to add and is more something to answer through your own build system / wrapper.

The ideal behind isomorphic/universal code is write once, run everywhere.  Having additional builds or wrappers for something that's technically already wrapped kind of defeats this idea.

The immediate issue I see with this is that hammer.js uses it's self invoking wrapper that hands in a specific window/document objects. There's no opportunity for us to 'cleanly' require it without it's initialise code from happening.

I also understand that you kind of want this done ASAP on the client side and test for specific support on launch - and only do this once.

So - it requires more thought on our side to present a nice clean and cross-environment compatible solution.  (I can't think of any of the top of my head other than this hack... which I won't encourage you to use).

From the top of my head I'd probably suggest something like passing in `this` or `self` instead of `window`, and pulling out `document = window.document || {}` - kind of what you do when hammer is loaded in AMD via a script tag, but considering the document as well.

The TEST_ELEMENT test though is still problematic without a DOM, which then goes on to be used in PREFIXED_TOUCH_ACTION.  The rest of hammer is all inside their own functions, and I don't feel like hammer should actually run inside node - so there'd be no further changes to global scope windows thereafter.

**Comment by arschmitz** [comment]
@darrennolan We talked about this last night some more. While this still seems not completely correct for a DOM library like hammer we decided we are going to check for a document and window and if none exist warn and return

**Comment by denis-sokolov** [comment]
It does not seem that my original PR applies anymore anyway.

**Pull request closed without merging**
