### PR TITLE
Adjust defaults to avoid detection gaps and make swipe more sensitive

### LINKED ISSUE #838: [META] Hammer's Default Configuration Leaves Gesture Detection Gaps
Gaps currently exist between pan and swipe, and between tap and press.  This is especially confusing for new users who just want to drop it in and play.

These gaps may be problematic for detecting any taps on some mobile devices.  A hypothesis is that this relates to pixel density.  The default tap movement threshold should likely be adjusted higher (to meet pan at 9px, possibly more), to avoid issues like #804 

Velocity settings (and default configuration) should be explained.  Most velocity values will lead to very few swipes being registered.  It's possible we might want to provide a few scenarios for when to use pan versus when to use swipe.  It seems much swipe usage is better suited for and likely intended to be pan usage, but the difference between the mental constructs is poorly understood.

The following affected issues are closed by this meta ticket.
- #804 
- #814

The following affected issues are not closed by this meta ticket.
- #776

### PR DESCRIPTION
**Pull request by runspired**
Resolves #838

### CODE REVIEW

**Comment by runspired** [comment]
Looks as though the current gaps were actually expected in the existing tests, will update those.

**Comment by ritterb82** [comment]
I just got done having to make these changes runspired suggested to fix the touch stuff for samsung Android. ( these defaults seem to work much better ).

Is there any update on when this will be officially merged and fixed.

**Comment by runspired** [comment]
@ritterb82 we just haven't had that time to fix the failing tests (there's a number of them).

**Comment by runspired** [comment]
Closing this as it's also in #860

**Pull request closed without merging**
