### PR TITLE
add feature that touch-action style is restored in Hammer.destroy

### PR DESCRIPTION
**Pull request by sculove**
#### feat(TouchAction): add originalTouchActionStyle property and some methods in TouchAction

touch-action style is not removed on destroy. (#853)
so, I add originalTouchActionStyle property for caching and some methods.
- add destroy, canApplyStyle methods in TouchAction.
- add PREFIXED_TOUCH_ACTION, NATIVE_TOUCH_ACTION in Hammer for testing.
- add 'test_touchaction.js' testcase

### CODE REVIEW

**Comment by arschmitz** [comment]
This is definitely  good idea we should always try to clean up after ourselves. will review in detail shortly

**Comment by arschmitz** [comment]
@sculove this looks good but it conflicts with changes we made for iOS 9.3 can you rebase and update?

**Comment by sculove** [comment]
@arschmitz ok I'll update it

**Comment by sculove** [comment]
I made a mistake. I close this pr. and then I'll other pr.

**Pull request closed without merging**
