### PR TITLE
Added middle and right button support.

### PR DESCRIPTION
**Pull request by tehnomaag**
By default Hammer only supported left-button mouse input.

Now this can be configured by passing in mouseButtons array to Hammer options object like so:

    Hammer(element, {
        // Left, mid and right buttons allowed
        mouseButtons: [0,1,2]
    });

PS: Handle and preventDefault the "contextmenu" event yourself for right-click dragging with Hammer to work properly in your document. Example:

    document.documentElement.addEventListener("contextmenu", function (ev) { ev.preventDefault(); });

### CODE REVIEW

**Comment by PabloK** [comment]
I would love if this could be merged.

**Comment by PabloK** [comment]
What would be needed to pull this in?

**Comment by arschmitz** [comment]
Hi we just started development and cleanup on hammer again and will look at this soon.

**Comment by runspired** [comment]
@PabloK @Firzenizer @tehnomaag could you provide a quick rundown of why you want middle / right button support?  Is this just to support mouse wheel events?

**Comment by Firzenizer** [comment]
@runspired We are using hammer.js in a drawing application. It is needed for wheel events for zooming and also right mouse dragging and some other stuff. Can't even remember all the uses.

**Comment by arschmitz** [comment]
@Firzenizer wheel zoom ( or mousewheel in general ) is not something we plan on supporting. There are other libraries that handle this already.

I just noticed this is also a PR on V1 so i'm going to close this since its un-mergable. Any one is interested in this feature still open an issue and we can discuss it there.

**Pull request closed without merging**
