### PR TITLE
Fix Firefox vendor prefix.

### PR DESCRIPTION
**Pull request by iclanzan**

### CODE REVIEW

**Comment by runspired** [comment]
@arschmitz This PR correct that the prefix for firefox touch events should be `Moz` not `moz`, but support was removed in Firefox 18, so I think we should close this in favor of removing the prefix altogether.

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events_%28Mozilla_experimental%29

**Comment by arschmitz** [comment]
I agree ill close it now

**Comment by SuperGouge** [comment]
Vote to reopen as this also affects styles set with ``manager.options.cssProps`` in ``toggleCssProps``. For example, this causes text to be selectable in Firefox.

**Comment by runspired** [comment]
@arschmitz We might want to consider @SuperGouge's thought there.  Will open a PR

**Pull request closed without merging**
