### PR TITLE
Swipe recognizer using overall gesture direction and velocity instead of last interval

### PR DESCRIPTION
**Pull request by annam**
Related to issue #640. Swipe recogniser should depend on overall direction (offsetDirection) and overall velocity (overallVelocity) instead of the ones of the last interval. Makes this more sensitive to swipes that slow down before touchend.

Added "overallVelocity" property in input which takes into account the total gesture time and the overall distance moved. 

Prerequisite to fix issue #639 where the inverse value was returned for offsetDirection, also fixed in this PR.

also added a fix for swipe incorrectly triggering after pinch/rotate if one finger touchends before the other.

### CODE REVIEW

**Comment by lobsterdore** [comment]
I think swipe is fairly broken until you apply this patch, this should be merged asap.

**Comment by neil-s** [comment]
Admins, could this PR be merged please?

**Comment by owenversteeg** [comment]
Probably not getting merged until #749 gets resolved, unfortunately

**Comment by arschmitz** [comment]
Hi we will look into this ASAP once we finish trying to clean up the issues a little. Hoping to do a quick patch release with this and some other fixes.

**Comment by runspired** [comment]
Related to #806, #748, #730

**Comment by arschmitz** [comment]
Reading over this i think this seems like the correct change

**Pull request closed without merging**
