### PR TITLE
Compatibility with requirejs optimizer namespaces #686

### PR DESCRIPTION
**Pull request by andreincx**
http://requirejs.org/docs/faq-optimization.html#namespace

See issue #686

### CODE REVIEW

**Comment by runspired** [comment]
@andreincx could you change this

```
typeof define === 'function'
```

to

```
var TYPE_FUNCTION = 'function';

if (typeof define === TYPE_FUNCTION && define.amd) {
```

To keep this consistent?

**Comment by meszarv** [comment]
@runspired `typeof define === TYPE_FUNCTION && define.amd` will not work with r.js
The check has to be exactly as andreincx fixed it, othervise r.js will not recognize it and the namespace is not applied.

**Comment by andreincx** [comment]
Sorry, I didn't have time to comment on that and forgot about issue. @meszarv  is right about it.

**Comment by runspired** [comment]
Hrm, we'll need to figure out something else then because `define` is present in many environments that aren't `amd` and would not load correctly with your approach.

**Comment by ahumphreys87** [comment]
any chance of a merge and release with this fix? I'm also hitting this issue

**Comment by arschmitz** [comment]
This will be in the next release

**Comment by LeJared** [comment]
Is there any schedule, when a new version will be released?
I don't ask for a specific date, but will it be in days, weeks or months?

**Comment by arschmitz** [comment]
as soon as we fix the failing tests on master its basically done

**Pull request closed without merging**
