### PR TITLE
fix(input): suppress mouse events after touch

### LINKED ISSUE #917: Tap fired twice in Chrome when using touch on Windows 8.1 / 10
When using Chrome with a touch screen on Windows 8.1 or Windows 10, tap gets fired twice.
First tap is fired on touchend and second on (emulated) mouseup.

Working Example:
http://codepen.io/LeJared/pen/ZQmrZK?editors=1011
(Watch Console)

I guess the mouseup should be ignored when tap was initiated by touchstart?

### PR DESCRIPTION
**Pull request by kara**
Quick fix to prevent duplicate taps on Surface

### CODE REVIEW

**Comment by BillBooks** [comment]
This seems too aggressive.   

Chrome doesn't seem to always send synthesized mouse events if the touch is a drag.   In that case, your next (possibly mush later) mouse session will get ignored.   That's only really a problem in cases where you want to allow both touch and mouse use --- I know I use my Surface like that when I have the type cover on, but I may be an outlier.

**Comment by kara** [comment]
Yeah, I agree there needs to be a more comprehensive solution.  Just wanted to get something in as a quick fix to make it usable at all on Surface.  It looks like a larger rewrite is currently being considered, so I'll close for now.

**Comment by runspired** [comment]
I think the approach forward is going to be that input sessions are channeled by source type, and gestures can only trigger within a given channel, not across channels.

**Comment by runspired** [comment]
@arschmitz thoughts?

**Comment by runspired** [comment]
If we actually build a channel primitive, this could help us with the linearly-composable gesture concept we've been bantering about.

**Comment by BillBooks** [comment]
That makes sense to me, it's the ideal we were trying to fake in our workaround to this issue.   About the only issue that we identified was the possibility that an accidental touch -- say brushing the screen --- might interfere with an in flight mouse gesture.    I can imagine fairly straightforward implementations of channelization that would handle this case properly where our workaround failed.

**Comment by arschmitz** [comment]
@runspired yes thats right that is for sure the way forward and what we have been discussing

**Pull request closed without merging**
