### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by abrin**
Missing ChangeLog entries for existing releases; please review

### CODE REVIEW

**Comment by arschmitz** [comment]
This is very incomplete. We use a script to generate are changelog and its is manually curated from that this will be updated soon.

**Comment by abrin** [comment]
sorry. Just trying to help as it’s not being updated automatically.

**Comment by arschmitz** [comment]
@abrin no problem appreciate the effort

**Comment by arschmitz** [comment]
@abrin the changelog is now update both in the repo and on the website

**Pull request closed without merging**
